/** Static asset paths — mirrors Flutter SImages */
export const images = {
  logo: "/images/logo.svg",
  logoLight: "/images/logo-light.svg",
  logoDark: "/images/logo-dark.svg",
  onboarding1: "/images/onboarding-1.svg",
  onboarding2: "/images/onboarding-2.svg",
  onboarding3: "/images/onboarding-3.svg",
  googleIcon: "/images/google-icon.svg",
  githubIcon: "/images/github-icon.svg",
  avatarPlaceholder: "/images/avatar-placeholder.svg",
  emptyMeetings: "/images/empty-meetings.svg",
  emptyChat: "/images/empty-chat.svg",
  emptyNotifications: "/images/empty-notifications.svg",
  emptyRecordings: "/images/empty-recordings.svg",
  noConnection: "/images/no-connection.svg",
  heroIllustration: "/images/hero-illustration.svg",
} as const;

/** Static copy strings — mirrors Flutter STexts */
export const strings = {
  app: { name: "SpeakUp", tagline: "Conference. Collaborate. Connect." },
  auth: {
    loginTitle: "Welcome Back",
    loginSubtitle: "Sign in to continue to SpeakUp",
    signUpTitle: "Create Account",
    signUpSubtitle: "Join SpeakUp to start conferencing",
    forgotPassword: "Forgot Password?",
    signInWithGoogle: "Continue with Google",
    signInWithGithub: "Continue with GitHub",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
  },
  home: {
    greeting: "Good {timeOfDay}",
    quickActions: "Quick Actions",
    newMeeting: "New Meeting",
    joinMeeting: "Join Meeting",
    scheduleMeeting: "Schedule Meeting",
    upcomingMeetings: "Upcoming Meetings",
  },
  meeting: {
    upcoming: "Upcoming",
    past: "Past",
    recurring: "Recurring",
    recordings: "Recordings",
    noMeetings: "No meetings yet",
    joinByCode: "Enter meeting code",
    participants: "Participants",
    muteAll: "Mute All",
    endCall: "End Call",
    shareScreen: "Share Screen",
    raiseHand: "Raise Hand",
    startRecording: "Start Recording",
  },
  chat: {
    title: "Chats",
    noChats: "No conversations yet",
    typeMessage: "Type a message...",
    searchChats: "Search chats",
  },
  settings: {
    title: "Settings",
    profile: "Profile",
    general: "General",
    darkMode: "Dark Mode",
    notifications: "Notifications",
    language: "Language",
    meetingDefaults: "Meeting Defaults",
    camera: "Camera On by Default",
    microphone: "Microphone On by Default",
    account: "Account",
    about: "About",
    signOut: "Sign Out",
    deleteAccount: "Delete Account",
  },
  landing: {
    heroTitle: "Video Conferencing,\nReimagined",
    heroSubtitle:
      "Crystal-clear meetings with enterprise security. Connect your team from anywhere.",
    ctaStart: "Get Started Free",
    ctaDemo: "Watch Demo",
    feature1Title: "HD Video & Audio",
    feature1Desc:
      "Crystal-clear quality powered by WebRTC and intelligent adaptive bitrate.",
    feature2Title: "End-to-End Encryption",
    feature2Desc:
      "Your conversations stay private with military-grade encryption.",
    feature3Title: "Real-Time Chat",
    feature3Desc:
      "Send messages, share files, and collaborate alongside your video calls.",
    feature4Title: "Screen Sharing",
    feature4Desc:
      "Share your screen, a window, or a tab with one click — works everywhere.",
    feature5Title: "Cloud Recordings",
    feature5Desc: "Record meetings and access them anytime from your dashboard.",
    feature6Title: "Cross Platform",
    feature6Desc:
      "Join from web, mobile, or desktop. No downloads required for web.",
    pricing: "Pricing",
    pricingFree: "Free",
    pricingPro: "Pro",
    pricingEnterprise: "Enterprise",
  },
} as const;
